import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body className={inter.className}>
				<div className="flex items-center flex-col mt-4 text-3xl font-serif ">
					<header className="bg-blue-100 p-[1rem] w-full ">
						<p>Header</p>
					</header>
					{children}
					<footer className="bg-gray-200 p-[1rem] w-full ">
						<p>Footer</p>
					</footer>
				</div>
			</body>
		</html>
	);
}
